# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-11 20:12
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171211_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0', max_length=128, null=True),
        ),
    ]
