# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-11 20:15
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20171211_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
